title: Zamiana między systemami
memory_limit: 262144 # in kB
time_limit: 5000 # in milliseconds

scores:
    1 : 20
    2 : 40
    3 : 40

# See https://github.com/sio2project/sinol-make/blob/main/example_package/config.yml for more options
sinol_task_id: zam
sinol_contest_type: oi
sinol_expected_scores:
  zam.cpp:
    expected:
      0: {points: 0, status: OK}
      1: {points: 20, status: OK}
      2: {points: 40, status: OK}
      3: {points: 40, status: OK}
    points: 100


sinol_static_tests: ["zam0.in", "zam1.in"]
