# Konfiguracja wygenerowana automatycznie na podstawie ustawien w serwisie main2
memory_limits: {'0': 264000, '1': 264000, '2': 264000, '3': 264000, '4': 264000}
scores: {1: 25, 2: 25, 3: 25, 4: 25}
time_limits: {'0': 1000, '1': 1000, '2': 1000, '3': 1000, '4': 1000}
title: Loch czarnoksiężnika
